{{- if .Values.resources.autoscaling.enable }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "generic-application.fullname" . }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "generic-application.fullname" . }}
  minReplicas: {{ .Values.resources.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.resources.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.resources.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.resources.autoscaling.targetMemoryUtilizationPercentage }}
{{- end }}
