{{- if .Values.persistence.enabled }}
{{- range .Values.persistence.volumes }}
{{- if not (or .existingClaim $.Values.persistence.existingClaim) }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "generic-application.name" $ }}{{ if $.Values.environment }}-{{ $.Values.environment }}{{ end }}-{{ .name }}
spec:
  accessModes:
  {{- range .accessModes }}
    - {{ . }}
  {{- end }}
  resources:
    requests:
      storage: {{ .size }}
  {{- if .storageClass }}
  storageClassName: {{ .storageClass }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}